[package]
name = "heartbeat"
version = "0.1.0"
edition = "2021"

[dependencies]
prometheus = "0.13"
tokio = { version = "1.0", features = ["full"] }
hyper = { version = "0.14", features = ["full"] }

[[bin]]
name = "heartbeat"
path = "src/main.rs"
